# Generated by Django 3.2.9 on 2021-11-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('game', models.CharField(max_length=32)),
                ('players', models.ManyToManyField(to='user_api.User')),
            ],
        ),
    ]
