# Generated by Django 3.2.9 on 2021-11-18 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_api', '0004_bracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments_api.tournament'),
        ),
    ]
