# Generated by Django 3.2.9 on 2021-11-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
        ('tournaments_api', '0005_alter_bracket_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='list',
            field=models.ManyToManyField(blank=True, to='user_api.User'),
        ),
    ]
