# Generated by Django 3.2.9 on 2021-11-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
        ('tournaments_api', '0008_alter_bracket_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='complete',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='champion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='champion', to='user_api.user'),
        ),
    ]
